# Generated by Django 4.1 on 2022-09-03 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=50)),
                ("picture", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="AuthorizeResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("scope", models.CharField(max_length=200)),
                ("expiration", models.IntegerField()),
                ("token_type", models.CharField(max_length=60)),
                ("state", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authO.userprofile",
                    ),
                ),
            ],
        ),
    ]
